"""add workspaces unique constraint and desc last_opened index

Revision ID: acb1d745f812
Revises: 65152c7c388a
Create Date: 2026-08-12 05:02:31.568073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb1d745f812'
down_revision: Union[str, None] = '65152c7c388a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_workspaces_last_opened'), table_name='workspaces')
    op.create_index('idx_workspaces_last_opened', 'workspaces', ['user_id', sa.literal_column('last_opened_at DESC')], unique=False)
    op.create_unique_constraint('uq_workspaces_user_root_path', 'workspaces', ['user_id', 'root_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspaces_user_root_path', 'workspaces', type_='unique')
    op.drop_index('idx_workspaces_last_opened', table_name='workspaces')
    op.create_index(op.f('idx_workspaces_last_opened'), 'workspaces', ['user_id', 'last_opened_at'], unique=False)
    # ### end Alembic commands ###
