"""add indexed_files table for rag file-level mtime/size pre-check

Revision ID: b94e63a41227
Revises: acb1d745f812
Create Date: 2026-08-12 09:28:51.293610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94e63a41227'
down_revision: Union[str, None] = 'acb1d745f812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'file_path', name='uq_indexed_files_workspace_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexed_files')
    # ### end Alembic commands ###
