from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.models.agent import AgentTask, AgentTaskStatus, AgentTaskStep


class AgentRepository(Protocol):
    async def create_task(self, task: AgentTask) -> AgentTask: ...

    async def get_task(self, task_id: UUID) -> AgentTask | None: ...

    async def list_tasks(self, workspace_id: UUID) -> list[AgentTask]: ...

    async def update_status(self, task_id: UUID, status: AgentTaskStatus) -> None: ...

    async def append_step(self, step: AgentTaskStep) -> AgentTaskStep: ...

    async def list_steps(self, task_id: UUID) -> list[AgentTaskStep]: ...

    async def update_step(self, step: AgentTaskStep) -> AgentTaskStep: ...
