from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.models.workspace import Workspace


class WorkspaceRepository(Protocol):
    async def get_by_id(self, workspace_id: UUID) -> Workspace | None: ...

    async def list_by_user(self, user_id: UUID) -> list[Workspace]: ...

    async def get_by_user_and_root_path(self, user_id: UUID, root_path: str) -> Workspace | None: ...

    async def create(self, workspace: Workspace) -> Workspace: ...

    async def update(self, workspace: Workspace) -> Workspace: ...

    async def delete(self, workspace_id: UUID) -> None: ...

    async def touch_last_opened(self, workspace_id: UUID) -> None: ...
